### ISSUE TITLE
not reporting boolean false only true 

### ISSUE THREAD

**Issue by dgutierrez1287** [crayfishx/hiera-http#15]
I am using couchdb and when I run a query on a boolean value if that boolean value is true it will be returned as true, if that boolean value is false it will be returned as not existing (nil). I have confirmed this is a result of this backend and not a larger hiera issue, when I ran the test with using hiera with json files it reported both true and false correctly.

**Comment by crayfishx** [comment]
Thanks @nemski sorry this slipped through the cracks
