### ISSUE TITLE
Question regarding the use of yaml backend along side the http backend

### ISSUE THREAD

**Issue by jbcraig** [crayfishx/hiera-http#37]
The 'paths' component seems to be a redundancy to the :hierachy: structure and becomes additional hierarchies to traverse.  I would have expected to define a base path and then the hierarchies would be added to that structure so that:

:hierarchies:
- a
- b

:paths:
- /conf
- /moreconf

would lookup keys in:
/conf/a
/conf/b
/moreconf/a
/moreconf/b

This would mimic the process that other backends use.  Just wanted your thoughts before I spent any time trying to implement this functionality?  Ultimately I would be rolling this up to the hiera_consul backend, which was inspired by your work.

**Comment by crayfishx** [comment]
Hmmm - I think that's a bit confusing, and pretty limiting.... most people who are running yam along side http use the backends very differently and each backend would have a different hierarchy.  This model seems to make a lot of assumptions about what the implementor wants to achieve...

**Comment by jbcraig** [comment]
I can see what your saying.  I suppose I could add some syntax sugar and append the :hierachies: only if the path end in a slash.  That however feels kinda magical and potentially confusing in its own right.  The only benefit would be that you could then work the hierachies either way, lending flexibility.  For my use case I was planning to move existing yaml into this backend, so my suggestion seemed logical.  But logic is in the eye of the beholder.

Thanks for your consideration.

**Comment by crayfishx** [comment]
@jbcraig Using jerakia as a backend might give you the flexibility you want...

**Comment by jbcraig** [comment]
Closing this aged issue. So long, and thanks for all the fish.
