### ISSUE TITLE
Trouble getting this working with puppetserver-2.1.2-1.el6.noarch

### ISSUE THREAD

**Issue by danieljamesscott** [crayfishx/hiera-http#38]
I'm having trouble getting this working with puppetserver-2.1.2-1.el6.noarch.

The error appears to be something to do with parsing the paths. In my hiera.yaml, I have:

    :paths:
        - /hiera/%{key}

When this is parsed, the %{key} value is simply removed, not transformed into the key value, so it makes a lookup against:
    /hiera/

I've logged out the data before and after the call to `parse_string`, and it's definitely line 50 causing the problem. Any ideas what could be causing this? I have hiera_http working fine with my old puppet server (2.7), so it must be a problem with my new server config, possibly the ruby version (2.0)?

I'm also having issues debugging this, because I have to modify my catalogue, run puppet, restart the puppetserver, run puppet again, then check the logs, any tips for debugging more efficiently?

**Comment by crayfishx** [comment]
## Summary

This doesn't appear to be a problem specificaly with hiera-http (or indeed hiera-mysql, see crayfishx/hiera-mysql#14) - I've done some testing on this using a dummy backend to try and isolate the problem

Heres what I've done with Puppet 4.0

```ruby
class Hiera
  module Backend
   class Dummy_backend
     def lookup(key, scope, order_override, resolution_type, context)
       test_data='foo bar %{key}'
       parsed=Backend.parse_string(test_data, scope, {"key" => key})
       Hiera.debug("unparsed: #{test_data} to parsed: #{parsed}")
       return { }
     end
   end
  end
end
```

This backend just called Backend.parse_answer with the key in the data, running Hiera from the 
command line seems to work...

```
$ hiera -c hiera.yaml my_key --debug
DEBUG: 2015-12-02 08:55:50 +0100: unparsed: foo bar %{key} to parsed: foo bar my_key
{}
```

However, when trying to do the same from a Puppet data binding we get different behaviour

```puppet
class test ( $my_key = 'bar' ) {
}
include test
```

```
$ puppet apply --hiera_config `pwd`/hiera.yaml test.pp  --debug
Debug: Runtime environment: puppet_version=4.3.0, ruby_version=2.0.0, run_mode=user, default_encoding=UTF-8
...
Debug: hiera(): unparsed: foo bar %{key} to parsed: foo bar
```

Note the fact that in the last example the parsed string does _not_ include the key

## Versions

At first I thought this may be a hiera problem, but now I'm thinking it's something within Puppet - all versions of Hiera seem to behave as expected, the problem arise with Puppet 4.0

Downing to Puppet 3.8.4/Hiera 1.3.4 it works fine

```
Debug: hiera(): unparsed: foo bar %{key} to parsed: foo bar test::my_key
```

Upgrading Hiera to 2.0.0 but still on Puppet 3.8.4
```
Debug: hiera(): unparsed: foo bar %{key} to parsed: foo bar test::my_key
```

Upgrade Hiera to 3.0.5 but still on Puppet 3.8.4
```
Debug: hiera(): unparsed: foo bar %{key} to parsed: foo bar test::my_key
```

Upgrrade Puppet to 4.0.0 (with hiera 3.0.5)
```
Debug: hiera(): unparsed: foo bar %{key} to parsed: foo bar
```

Im still doing some debugging on this issue but will probably raise this with puppet labs as it seems very odd behaviour...

**Comment by crayfishx** [comment]
Edit:  I have also tried modifying the code according to the 2.x API with....

```ruby
class Hiera
  module Backend
   class Dummy_backend
     def lookup(key, scope, order_override, resolution_type, context={})
       test_data='foo bar %{key}'
       parsed=Backend.parse_string(test_data, scope, {"key" => key}, {:recurse_guard => context[:recurse_guard], :order_override => order_override})
       Hiera.debug("Key is #{key} of type #{key.class}")
       Hiera.debug("unparsed: #{test_data} to parsed: #{parsed}")
       return { }
     end
   end
  end
end
```

I still get the same behaviour

**Comment by crayfishx** [comment]
I've opened up https://tickets.puppetlabs.com/browse/HI-484 against this

**Comment by crayfishx** [comment]
@danieljamesscott et al, the fix for this is now merged and expected to release with Puppet 4.3.2, see https://github.com/puppetlabs/puppet/pull/4482 and https://tickets.puppetlabs.com/browse/PUP-5578

**Comment by danieljamesscott** [comment]
Excellent. Thanks for looking into this, and getting it fixed so promptly.

**Comment by danieljamesscott** [comment]
I'm running into problems when the key contains a '.'. This used to work, can you confirm whether this should be supported now, or is it deprecated in puppet 4?

**Comment by crayfishx** [comment]
@danieljamesscott See the comment by Hendrik on https://tickets.puppetlabs.com/browse/HI-485 - keys containing "." are not supported as they are used for accessing elements of hashes/arrays.

From our (hiera-http) perspective, theres not a lot we can do.

**Comment by danieljamesscott** [comment]
Thanks
