### ISSUE TITLE
Hiera 5 support

### ISSUE THREAD

**Issue by dzeleski** [crayfishx/hiera-http#47]
Are there any plans of supporting hiera 5? Puppet changed how backends are built and it definitely is much easier to build as its basically just a puppet function now: 

https://docs.puppet.com/puppet/4.9/hiera_custom_backends.html
https://docs.puppet.com/puppet/4.9/hiera_custom_lookup_key.html

Deprecation is set for puppet 6 so there is plenty of time to migrate. We are not using Hiera 5 yet but I figured id at least get this open as there are some really cool features in 5 that you do not need to fully migrate over to get.

**Comment by crayfishx** [comment]
Yep - this is totally planned and hopefully will get released soon

**Comment by dzeleski** [comment]
Awesome, thank you!
