### ISSUE TITLE
Lookups are very slow

### ISSUE THREAD

**Issue by jacobtomlinson** [crayfishx/hiera-http#9]
I am finding that lookups are very slow, to the extent where sometimes it times out and the puppet run fails.

This could of course be down to the web server providing the json.

It does seem make an http request every time it looks up something even if it has already looked up that file during that run.

Do you have any recommendations for working around this, e.g caching?

**Comment by erik-stephens** [comment]
Based on https://github.com/puppetlabs/hiera/pull/98 and what I've heard in #puppet, I think it's up to the backend to support caching.

**Comment by crayfishx** [comment]
@erik-stephens PR #18 currently has a proposal for caching which I'll try and get merged into the codebase this week if it looks good.

**Comment by erik-stephens** [comment]
Excellent!  I've been using that version for about a week now without issues.

**Comment by crayfishx** [comment]
#18 has been merged, thank you to all who contributed and commented.
